# Debug mode
debug: 1 # True/False

# OpenCV settings
opencv:
  lowThresh: [0, 0, 0]
  highThresh: [255, 255, 255]
  canny: 1
  width: 640
  height: 360
  saveFiles: 1 # True/False
  
# B, G, R
GREEN: [0,255,0]
BLUE: [255,0,0]
RED: [0,0,255]
WHITE: [255,255,255]
YELLOW: [0,255,255]