# Debug mode
debug: 0 # True/False

# AR.Drone settings
ardrone:
  ip1: 192.168.1.10
  ip2: 192.168.1.11
  turnSpeed: 0.25 # 0 to 1
  FBSpeed: 0.1 # 0 to 1
  LRSpeed: 0.1 # 0 to 1
  UDSpeed: 0.1 # 0 to 1
  color: [235,20,20]
  threshold: 50 # +/- for target color
  nIters: 10
  minArea: 1500
  dissize: 175

# target0 color and whitebalance from static photo (lightsaber theater)
target0:
  color: [252,226,134]
  whiteBalance: 45
  threshold: 50 # +/- for target color
  nIters: 10
  minArea: 100
  dissize: 150

# target1 color and whitebalance from static photo (lightsaber upstairs)
target1:
  color: [255,253,69]
  whiteBalance: 115
  threshold: 25 # +/- for target color
  nIters: 10
  minArea: 500
  dissize: 150
  
# target3 color and whitebalance from static photo (laser upstairs)
target3:
  color: [198,246,159]
  whiteBalance: 137
  threshold: 30 # +/- for target color
  nIters: 1
  minArea: 10
  dissize: 100
  
# target4 color and whitebalance from static photo (laser upstairs)
target4:
  color: [70,86,166]
  whiteBalance: 45
  threshold: 30 # +/- for target color
  nIters: 10
  minArea: 10
  dissize: 200

# OpenCV settings
opencv:
  lowThresh: 0
  highThresh: 1
  width: 640
  height: 360
  saveFiles: 0 # True/False
  
# Camera
camera:
  ip: 192.168.1.20
  port: 80
  username: root
  password: CSC
  resolution: 640x480
  compression: 30
  fps: 10
  
# B, G, R
GREEN: [0,255,0]
BLUE: [255,0,0]
RED: [0,0,255]
WHITE: [255,255,255]
YELLOW: [0,255,255]